import os

from decouple import config

SOURCE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SOURCE_DIR)

RUN_STREAM_TO_BUFFER_SCRIPT = config('RUN_STREAM_TO_BUFFER_SCRIPT', default='run_stream_to_buffer.py')
RUN_STREAM_TO_BUFFERS = os.path.join(SOURCE_DIR, RUN_STREAM_TO_BUFFER_SCRIPT)

REDIS_ADDRESS = config('REDIS_ADDRESS', default='localhost')
REDIS_PORT = config('REDIS_PORT', default='6379')
REDIS_EXPIRATION_TIME = config('REDIS_EXPIRATION_TIME', default=30)


TRACER_REPORTING_HOST = config('TRACER_REPORTING_HOST', default='localhost')
TRACER_REPORTING_PORT = config('TRACER_REPORTING_PORT', default='6831')

SERVICE_STREAM_KEY = config('SERVICE_STREAM_KEY')

LISTEN_EVENT_TYPE_QUERY_CREATED = config('LISTEN_EVENT_TYPE_QUERY_CREATED')
LISTEN_EVENT_TYPE_QUERY_REMOVED = config('LISTEN_EVENT_TYPE_QUERY_REMOVED')

SERVICE_CMD_KEY_LIST = [
    LISTEN_EVENT_TYPE_QUERY_CREATED,
    LISTEN_EVENT_TYPE_QUERY_REMOVED,
]


PUB_EVENT_LIST = [
]


SERVICE_DETAILS = None


LOGGING_LEVEL = config('LOGGING_LEVEL', default='ERROR')

FFMPEG_BIN = config('FFMPEG_BIN', default='ffmpeg')

